name: 'SSH Agent Setup'
description: 'Set up ssh-agent and add keys & passphrase on the runner.'
author: 'Raghav Marwaha'
branding:
  icon: 'activity'
  color: 'red'
inputs:
  ANSIBLE_SSH_KEY:
    description: 'SSH private key to add to the agent.'
    required: true
  SSH_KEY_PASSPHRASE:
    description: 'Passphrase for the SSH key.'
    required: true
  SSH_AUTH_SOCK:
    description: 'Socket file Path for ssh-agent.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'

        

