name: 'SSH Agent Setup'
description: 'Set up ssh-agent and add keys & passphrase on the runner.'
author: 'Raghav Marwaha'
branding:
  icon: 'activity'
  color: 'red'
inputs:
  ANSIBLE_SSH_KEY:
    description: 'SSH private key to add to the agent.'
    required: true
  SSH_KEY_PASSPHRASE:
    description: 'Passphrase for the SSH key.'
    required: true
  SSH_AUTH_SOCK:
    description: 'Socket file Path for ssh-agent.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Remove old SSH_AUTH_SOCKET and SSH-AGENT Instance'
      run: |
          rm /tmp/ssh_agent.sock
          unset SSH_AUTH_SOCK
          pkill ssh-agent
      continue-on-error: true
      shell: bash

    - name: Execute Python script
      shell: bash
      run: python3 ssh_agent_ansible.py
      env:
        ANSIBLE_SSH_KEY: ${{ inputs.ANSIBLE_SSH_KEY }}
        SSH_KEY_PASSPHRASE: ${{ inputs.SSH_KEY_PASSPHRASE }}
        SSH_AUTH_SOCK: ${{ inputs.SSH_AUTH_SOCK }}
        

