name: 'SSH Agent Setup'
description: 'Set up ssh-agent and add keys & passphrase on the runner.'
author: 'Raghav Marwaha'
inputs:
  ANSIBLE_SSH_KEY:
    description: 'SSH private key to add to the agent.'
    required: true
  SSH_KEY_PASSPHRASE:
    description: 'Passphrase for the SSH key.'
    required: true
  SSH_AUTH_SOCK:
    description: 'Socket file Pathfor ssh-agent.'
    required: true
runs:
  using: 'node12' # Specify the Node version
  main: 'index.js' # Your JavaScript entry point
