name: Pipeline for Testing @Action for ansible infrastructure with SSH-AGENT Automation on github hosted Runners
run-name: "Pipeline Executed by ${{github.actor}}"
on: [workflow_dispatch]
jobs:
  Run-Action-Pipeline-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2
        
      - name: Execute Key & passphrase Storage with SSH-AGENT
        uses: marwaha-raghav/ssh-agent-ansible@main
        with:
          SSH_AUTH_SOCK: "/tmp/ssh_agent.sock"
          SSH_KEY_PASSPHRASE: ${{secrets.SSH_KEY_PASSPHRASE}}
          ANSIBLE_SSH_KEY: ${{secrets.ANSIBLE_SSH_KEY}}

      - name: Install ansible
        run: apt install ansible
        shell: bash
        
      - name: 'Check ansible version'
        run: ansible --version

      - name: 'Run the Test playbook'
        env:  
          SSH_AUTH_SOCK: "/tmp/ssh_agent.sock"
        run: ansible-playbook -i ./tests/inventory --limit 'dev_nodes' ./tests/hello-world.yml