name: Pipeline for Testing ansible infrastructure
run-name: Running hello world test playbook
on: [workflow_dispatch]
jobs:
  Run-Test-Playbooks:
    runs-on: self-hosted
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2
        
      - name: 'Remove old SSH_AUTH_SOCKET and SSH-AGENT Instance'
        run: |
          rm /tmp/ssh_agent.sock
          unset SSH_AUTH_SOCK
          pkill ssh-agent
        continue-on-error: true

      - name: Setup SSH Agent
        env:
          SSH_AUTH_SOCK: "/tmp/ssh_agent.sock"
          SSH_KEY_PASSPHRASE: ${{secrets.SSH_KEY_PASSPHRASE}}
          ANSIBLE_SSH_KEY: ${{secrets.ANSIBLE_SSH_KEY}}
        run: ./run.sh
        shell: bash
      
      - name: 'Check ansible version'
        run: ansible --version

      - name: 'Run the hello world playbook'
        run: ansible-playbook -i ./inventory --limit 'dev_nodes' ./hello-world.yml