name: Pipeline for Testing Action for ansible infrastructure with SSH-AGENT Automation
run-name: "Pipeline Executed by ${{github.actor}}"
on: [workflow_dispatch]
jobs:
  Run-Action-Pipeline:
    runs-on: self-hosted
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: 'Remove old SSH_AUTH_SOCKET and SSH-AGENT Instance'
        run: |
          rm /tmp/ssh_agent.sock
          unset SSH_AUTH_SOCK
          pkill ssh-agent
        continue-on-error: true
        
      - name: Execute Key & passphrase Storage with SSH-AGENT
        uses: marwaha-raghav/ssh-agent-ansible@main
        with:
          SSH_AUTH_SOCK: "/tmp/ssh_agent.sock"
          SSH_KEY_PASSPHRASE: ${{secrets.SSH_KEY_PASSPHRASE}}
          ANSIBLE_SSH_KEY: ${{secrets.ANSIBLE_SSH_KEY}}

      - name: 'Check ansible version'
        run: ansible --version

      - name: 'Run the Test playbook'
        env:  
          SSH_AUTH_SOCK: "/tmp/ssh_agent.sock"
        run: ansible-playbook -i ./tests/inventory --limit 'dev_nodes' ./tests/hello-world.yml
